"use client";
import { useState, type ReactNode } from "react";
import { readAgent, checkAgentEndpoint } from "./client";
import type { AgentDetail, BnbChain, EndpointProof } from "./types";
import { bnbHref } from "./marketplace/journey";

export function ProviderWorkspace({ chainId, address, signIn }: { chainId: BnbChain; address?: string; signIn: ReactNode }) {
  const [id,setId]=useState(""); const [agent,setAgent]=useState<AgentDetail|null>(null); const [proof,setProof]=useState<EndpointProof|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const button="inline-flex min-h-11 items-center justify-center border border-[color:var(--hairline-strong)] px-4 py-3 text-sm focus-visible:outline focus-visible:outline-accent disabled:opacity-50";
  if(!address)return <section className="border border-[color:var(--hairline)] p-6"><p className="mb-5 text-sm text-ink-2">Sign in to inspect the services owned by your wallet.</p>{signIn}</section>;
  return <div className="space-y-6"><section className="border border-[color:var(--hairline)] bg-canvas-2 p-6"><h2 className="font-stencil text-2xl uppercase">Your published service</h2><p className="mt-3 text-sm leading-relaxed text-ink-2">Enter a registered agent ID. AGON checks the current owner on this network before displaying it here. A complete owner directory is not available yet.</p><form className="mt-5 flex flex-wrap gap-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");setAgent(null);setProof(null);try{const result=await readAgent(chainId,id);if(result.owner.toLowerCase()!==address.toLowerCase())throw new Error("This agent is not owned by your signed-in wallet on this network.");setAgent(result);}catch(e){setError(e instanceof Error?e.message:"Could not read this service.");}finally{setBusy(false);}}}><label className="min-w-0 flex-1 text-sm">Agent ID<input className="mt-2 min-h-12 w-full border border-[color:var(--hairline-strong)] bg-canvas p-3" required inputMode="numeric" pattern="[0-9]+" value={id} onChange={e=>setId(e.target.value)} /></label><button className={`${button} self-end bg-accent text-accent-ink`} disabled={busy}>{busy?"Loading…":"Open service →"}</button></form>{error?<p role="alert" className="mt-4 text-sm">{error}</p>:null}</section>
    {agent?<section className="border border-[color:var(--hairline)] bg-canvas-2 p-6"><h2 className="font-stencil text-3xl uppercase">{agent.name}</h2><p className="mt-3 text-sm text-ink-2">{agent.description}</p><p className="mt-4 break-all font-mono text-xs">Version: {agent.versionHash??"Unavailable"}</p><div className="mt-5 flex flex-wrap gap-3"><a className={button} href={bnbHref(chainId,`/market/${agent.id}`)}>View buyer page →</a><a className={button} href={bnbHref(chainId,"/market/new")}>Publish service →</a><button className={button} disabled={busy} onClick={async()=>{setBusy(true);setError("");try{setProof(await checkAgentEndpoint(chainId,agent.id));}catch(e){setError(e instanceof Error?e.message:"Could not check service.");}finally{setBusy(false);}}}>Check connection</button></div>{proof?<p role="status" className="mt-4 text-sm text-ink-2">{proof.message} Checked {new Date(proof.checkedAt).toLocaleString()}. Task delivery is not tested by this check.</p>:null}</section>:null}
    <section className="border border-[color:var(--hairline)] p-6"><h2 className="font-stencil text-2xl uppercase">Provider operations</h2><p className="mt-3 text-sm leading-relaxed text-ink-2">Pending releases, delivery queues, session controls and earnings are not exposed by the provider API yet. No revenue, job count or active session is inferred from directory data.</p><a className={`${button} mt-5`} href={bnbHref(chainId,"/market/activity")}>View your buyer activity →</a></section></div>;
}
