"use client";
import { useState } from "react";
import type { LpHiringReadiness } from "./types";
import type { LpInput } from "./providers/lp-core";
import { validateReportInput } from "./marketplace/journey";

const BUTTON = "inline-flex min-h-11 items-center justify-center border border-[color:var(--hairline-strong)] px-4 py-3 font-mono text-xs uppercase text-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent disabled:opacity-50";
const INPUT = "mt-2 min-h-12 w-full border border-[color:var(--hairline-strong)] bg-canvas p-3 text-sm text-ink";

export function ReportConfiguration({ readiness, version, busy, signedIn, signIn, submit }: { readiness: LpHiringReadiness; version: string; busy: boolean; signedIn: boolean; signIn: () => void; submit: (input: LpInput) => void }) {
  const [step, setStep] = useState(0); const [position, setPosition] = useState(""); const [width, setWidth] = useState("10"); const [deviation, setDeviation] = useState("100");
  const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const draftKey = `agon:report-draft:${readiness.chainId}:${readiness.agentId}:${version}`;
  function save() {
    try { sessionStorage.setItem(draftKey, JSON.stringify({position,width,deviation})); setNotice("Draft saved in this tab. No request or payment has been started."); } catch { setError("This browser cannot save a draft. You can still continue without saving."); }
  }
  function resume() {
    try { const raw = sessionStorage.getItem(draftKey); if (!raw) { setNotice("No draft saved for this service version in this tab."); return; } const value = JSON.parse(raw); if (![value.position,value.width,value.deviation].every(v=>typeof v==="string")) throw new Error(); setPosition(value.position); setWidth(value.width); setDeviation(value.deviation); setStep(0); setNotice("Draft restored. Review the current price and permissions again."); } catch { setError("Could not restore this draft. Enter the position again."); }
  }
  function next() { const invalid=validateReportInput(position,width,deviation); if(invalid){setError(invalid);return;} setError(""); setStep(s=>s+1); }
  return <div className="mt-6 space-y-5">
    <ol className="grid grid-cols-3 gap-2" aria-label="Prepare report"><li aria-current={step===0?"step":undefined} className={`border p-3 text-sm ${step===0?"border-accent":"border-[color:var(--hairline)]"}`}>1. Configure</li><li aria-current={step===1?"step":undefined} className={`border p-3 text-sm ${step===1?"border-accent":"border-[color:var(--hairline)]"}`}>2. Permissions</li><li aria-current={step===2?"step":undefined} className={`border p-3 text-sm ${step===2?"border-accent":"border-[color:var(--hairline)]"}`}>3. Review</li></ol>
    <form onSubmit={e=>{e.preventDefault(); if(step<2){next();return;} const invalid=validateReportInput(position,width,deviation); if(invalid){setError(invalid);setStep(0);return;} if(!signedIn){save();signIn();return;} submit({positionId:position,halfWidthSteps:Number(width),maxDeviationTicks:Number(deviation)});}}>
      <fieldset disabled={busy} className="min-w-0 space-y-5"><legend className="sr-only">{["Configure your report","Review permissions","Review and continue"][step]}</legend>
      {step===0?<><label className="block text-sm">PancakeSwap position ID<input className={INPUT} required inputMode="numeric" pattern="[0-9]+" value={position} onChange={e=>setPosition(e.target.value)} placeholder="Enter the ID from your position"/><span className="mt-2 block text-xs text-ink-2">The number shown on your PancakeSwap position. This report does not change it.</span></label><details><summary className="min-h-11 cursor-pointer py-3 text-sm">Advanced report settings</summary><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">Range size (steps)<input className={INPUT} type="number" min="1" max="1000" step="1" value={width} onChange={e=>setWidth(e.target.value)}/></label><label className="block text-sm">Maximum price deviation (ticks)<input className={INPUT} type="number" min="0" max="10000" step="1" value={deviation} onChange={e=>setDeviation(e.target.value)}/></label></div><p className="mt-3 text-sm text-ink-2">These control the proposed range width and permitted difference from the recent average price.</p></details></>:null}
      {step===1?<><h4 className="font-stencil text-2xl uppercase">What you are authorizing</h4><ul className="list-disc space-y-3 pl-5 text-sm leading-relaxed text-ink-2"><li>One report payment of {readiness.priceDisplay} {readiness.token?.symbol}. Network fees are separate.</li><li>No permission to trade, rebalance or withdraw from your position.</li><li>No recurring allowance or autonomous session is created by this report flow.</li><li>Your wallet will confirm request setup, the service, the token approval and payment separately.</li></ul><p className="text-sm text-ink-2">The exact recipient, request expiry and token amount appear with the prepared request before you sign. Token approval may remain after a request expires; this interface does not provide a revoke control.</p></>:null}
      {step===2?<><h4 className="font-stencil text-2xl uppercase">Review your report</h4><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-ink-2">Position</dt><dd className="mt-2 break-all">{position}</dd></div><div><dt className="text-ink-2">Price</dt><dd className="mt-2">{readiness.priceDisplay} {readiness.token?.symbol} per report</dd></div><div><dt className="text-ink-2">Network</dt><dd className="mt-2">BNB Testnet · test funds only</dd></div><div><dt className="text-ink-2">Fees</dt><dd className="mt-2">Your wallet estimates tBNB network fees for each step.</dd></div><div className="sm:col-span-2"><dt className="text-ink-2">Exact metadata version</dt><dd className="mt-2 break-all font-mono text-xs">{version}</dd></div></dl><p className="text-sm leading-relaxed text-ink-2">You receive a read-only position report, not an automated rebalance. Continuing prepares a request. It does not approve payment. Receipts and delivery will appear in Activity.</p></>:null}
      <div className="flex flex-wrap gap-3">{step>0?<button className={BUTTON} type="button" onClick={()=>{setStep(s=>s-1);setError("");}}>Back</button>:null}<button className={`${BUTTON} bg-accent !text-accent-ink`} type="submit">{busy?"Preparing request…":step===0?"Review permissions →":step===1?"Review report →":signedIn?"Prepare request →":"Sign in to continue →"}</button></div>
      </fieldset>
    </form>
    <div className="flex flex-wrap gap-3"><button type="button" className={BUTTON} onClick={save} disabled={busy}>Save draft</button><button type="button" className={BUTTON} onClick={resume} disabled={busy}>Resume draft</button></div>
    {notice?<p role="status" className="text-sm text-ink-2">{notice}</p>:null}{error?<p role="alert" className="border-l-2 border-accent pl-3 text-sm">{error}</p>:null}
  </div>;
}
