"use client";

import { useState } from "react";
import { createStaffAccount, disableStaffAccount, listStaffAccounts, type StaffAccountRecord } from "@/lib/support";

export function SupportStaffSetup() {
  const [token, setToken] = useState(""); const [staff, setStaff] = useState<StaffAccountRecord[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [unlocked, setUnlocked] = useState(false);
  async function load(value = token) { setBusy(true); setError(""); try { const result = await listStaffAccounts(value); setStaff(result.staff); setUnlocked(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Access failed"); } finally { setBusy(false); } }
  async function create(form: FormData) { setBusy(true); setError(""); try { await createStaffAccount(token, { email: String(form.get("email") ?? ""), displayName: String(form.get("displayName") ?? ""), password: String(form.get("password") ?? ""), role: String(form.get("role") ?? "support") }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Account could not be created"); } finally { setBusy(false); } }
  if (!unlocked) return <div className="grid gap-4 border border-[color:var(--hairline-strong)] bg-canvas-2 p-7"><label className="grid gap-2 font-mono text-[11px] uppercase tracking-[0.12em] text-ink-2">Owner admin token<input value={token} onChange={(event) => setToken(event.target.value)} type="password" autoComplete="off" className="min-h-12 border border-[color:var(--hairline-strong)] bg-canvas px-4 font-sans text-sm normal-case tracking-normal text-ink outline-none focus:border-accent" /></label>{error ? <p role="alert" className="font-mono text-xs text-danger">{error}</p> : null}<button disabled={busy || !token} onClick={() => void load()} className="min-h-12 bg-accent px-6 font-mono text-xs uppercase tracking-[0.12em] text-canvas disabled:opacity-50">Open team setup</button></div>;
  return <div className="grid gap-8"><form action={create} className="grid gap-4 border border-[color:var(--hairline-strong)] bg-canvas-2 p-7"><h2 className="font-sans text-xl font-semibold">Add a teammate</h2><div className="grid gap-4 md:grid-cols-2"><input required name="displayName" minLength={2} maxLength={80} placeholder="Display name" className="min-h-12 border border-[color:var(--hairline-strong)] bg-canvas px-4 text-sm" /><input required name="email" type="email" placeholder="Work email" className="min-h-12 border border-[color:var(--hairline-strong)] bg-canvas px-4 text-sm" /><input required name="password" type="password" minLength={12} maxLength={128} placeholder="Temporary password" className="min-h-12 border border-[color:var(--hairline-strong)] bg-canvas px-4 text-sm" /><select name="role" className="min-h-12 border border-[color:var(--hairline-strong)] bg-canvas px-4 text-sm"><option value="support">Support</option><option value="technical">Technical support</option></select></div><p className="font-mono text-[10px] leading-relaxed text-ink-3">Share the temporary password privately. The teammate must replace it at first sign-in.</p>{error ? <p role="alert" className="font-mono text-xs text-danger">{error}</p> : null}<button disabled={busy} className="min-h-12 bg-accent px-6 font-mono text-xs uppercase tracking-[0.12em] text-canvas">Create account</button></form><section className="border border-[color:var(--hairline-strong)]"><header className="border-b border-[color:var(--hairline)] p-5"><h2 className="font-sans text-xl font-semibold">Support team</h2></header>{staff.length === 0 ? <p className="p-5 text-sm text-ink-3">No staff accounts yet.</p> : staff.map((person) => <div key={person.staff_id} className="flex flex-wrap items-center justify-between gap-4 border-b border-[color:var(--hairline)] p-5 last:border-0"><div><p className="font-sans text-sm font-semibold">{person.display_name}</p><p className="mt-1 font-mono text-[10px] text-ink-3">{person.email} · {person.role} · {person.status}</p></div>{person.status === "active" ? <button onClick={() => void disableStaffAccount(token, person.staff_id).then(() => load())} className="min-h-11 border border-danger px-4 font-mono text-[10px] uppercase tracking-[0.1em] text-danger">Disable</button> : null}</div>)}</section></div>;
}
